version: '3.9'

services:
  mongo:
    image: mongo:5
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: deeploma
  s3:
    image: scireum/s3-ninja:latest
    ports:
      - 9444:9000
    volumes:
      - s3_data:/home/sirius/data
volumes:
  s3_data:
